{
 "title": "Rust Service - Live Benchmark",
 "refresh": "5s",
 "panels": [
  {
   "title": "GET Latency (p90) Seconds /api/item/{id}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=\"rust\", path=\"/api/item/{id}\"}[10s])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "CPU cores used  1.0 = 1 core (rust-service container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\", cpu=\"total\", id=~\"/docker/ddc069f3a8cf.*\"}[$__rate_interval]))",
     "legendFormat": "rust-service"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{job=\"rust\", path=\"/api/item/{id}\"}[10s]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "App Memory Usage (rust-service container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\", id=~\"/docker/ddc069f3a8cf.*\"}",
     "legendFormat": "rust-service"
    }
   ]
  }
 ]
}